export const MAX_ZOOM_LEVEL = 23;
export const MIN_SCALE = 70.5310735;
export const MAP_FEATURES_PORTAL_HOST_NAME = 'MAP_FEATURES_PORTAL_HOST_NAME';
export const LINE_BUILDER_POINT_LAYER = 'LINE_BUILDER_POINT_LAYER';
export const LINE_BUILDER_LINE_LAYER = 'LINE_BUILDER_LINE_LAYER';
export const MAP_CONTROLS_PORTAL_HOST_NAME = 'MAP_CONTROLS_PORTAL_HOST_NAME';
